### PR TITLE
Improve staffer

### PR DESCRIPTION
**Pull request by TomekFraczek**
The staffer views were sorely lacking in terms of detail and functionality. 
#95 

Added features:
  - Staffer now have full profile pages (similar to profile pages)
  - Staffers now have a boolean `is_active` that determines whether they are an active staffer or not
  - Nickname, Full Name, Title, Email are now displayed in list view
  - List view is sorted so that active staffers display first

### CODE REVIEW

**Comment by TomekFraczek** [comment]
Right, forgot that's the new workflow. Will do ASAP.

I had to add a few fields in the database populating, so maybe something there broke? I'll look into that as well.

**Comment by TomekFraczek** [comment]
One merge mayhem later... I believe we have a fully working version. How do I deploy it to dev so I can test things?

**Comment by estensen** [comment]
When the code is merged with the `dev` branch it is automatically deployed to Heroku.
After testing that deployment feel free to merge with the `master` branch and deploy it to production :)

**Comment by TomekFraczek** [comment]
Oh man that's fancy

**Pull request merged**
